name: Vishal Arya
bio: 'I always seems to smile'
external-image: true
picture: 'assets/images/profile.jpg'

url: http://myfj.github.io/
permalink: /:title/
#resume: true
#resume-external: true


markdown: kramdown
highlighter: rouge

analytics: 'UA-120753506-1'
#disqus: mydisqus
facebook: myfantasticj
twitter: myfantasticj
medium : myfantasticj
linkedin: vishal-arya-29940b132/
#youtube: myyoutube
github: myfj
instagram: myfantasticjourney
#quora: vishal-arya-41
email: work8vishal@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]
markdown: kramdown
highlighter: rouge

#analytics-google: 'UA-51322118-1'

# if you don't want comments in your posts, set to false
#disqus: 

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
#blog: false

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: true

#pagination
paginate: 5
paginate_path: "blog/page:num/"



gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
