name: Vishal Arya
bio: 'I always seems to smile'
picture: 'assets/images/profile.jpg'

url: http://myfj.github.io/
permalink: /:title/

#analytics: 'UA-73836399-1'
#disqus: mydisqus
facebook: myfantasticj
twitter: myfantasticj
linkedin: in/vishal-arya-29940b132/
#youtube: myyoutube
github: myfj
quora: vishal-arya-41
email: work8.vishal@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

#pagination
paginate: 5
paginate_path: "blog/page:num/"
# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"


gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
